name: map
description: "A flutter app built for google map integration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  flutter_dotenv: ^6.0.0
  custom_info_window: ^1.0.1
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  cherry_toast: ^1.13.0
  font_awesome_flutter: ^10.12.0
  flutter_google_places_sdk: ^0.4.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - .env
